// <auto-generated />
using HydrahajoAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HydrahajoAPI.Migrations
{
    [DbContext(typeof(HydrahajoDBContext))]
    [Migration("20260618182009_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HydrahajoAPI.Models.Component", b =>
                {
                    b.Property<int>("Component_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Component_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Component_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Component_Id");

                    b.ToTable("components");
                });
#pragma warning restore 612, 618
        }
    }
}
